version: '3.8'

services:
  thumbnail-maker:
    build: .
    container_name: thumbnail-maker
    restart: always
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./backend/temp:/app/backend/temp